using SB.Core;
using Serilog;
using System.Collections.Concurrent;
using System.Diagnostics;

namespace SB;

using BS = BuildInstance;

public class CompileCommandsEmitter : TaskEmitter
{
    public CompileCommandsEmitter(IToolchain Toolchain) => this.Toolchain = Toolchain;
    public IReadOnlyCollection<CompileCommandEntry> Entries => _compileCommandEntries.ToArray();

    public override bool EnableEmitter(BuildInstance Instance, Target Target) =>
        (Target.GetTargetType() == TargetType.HeaderOnly) || HasCFamilyFiles(Target);

    public override bool EmitTargetTask(BuildInstance Instance, Target Target) => Target.GetTargetType() == TargetType.HeaderOnly || HasCFamilyFiles(Target);
    public override IArtifact? PerTargetTask(BuildInstance Instance, Target Target)
    {
        // generate a dummy source file that includes all headers in IncludeDirs
        if (Target.GetTargetType() == TargetType.HeaderOnly)
        {
            if (Target.PublicArguments.TryGetValue("IncludeDirs", out var ArgList))
            {
                if (ArgList is ArgumentList<string> IncludeDirs)
                {
                    // Generate a source file for compile commands
                    var DstDirectory = Path.Combine(Target.GetBuildGenDir(), "compile_commands");
                    if (!Directory.Exists(DstDirectory))
                        Directory.CreateDirectory(DstDirectory);
                    string SourceFile = Path.Combine(DstDirectory, BS.GetUniqueTempFileName(Target.Name, "compile_commands", "cpp"));
                    // get & include all headers in IncludeDirs
                    var IncludeFiles0 = IncludeDirs.SelectMany(D => Directory.GetFiles(D, "*.h", SearchOption.AllDirectories));
                    var IncludeFiles1 = IncludeDirs.SelectMany(D => Directory.GetFiles(D, "*.hpp", SearchOption.AllDirectories));
                    var IncludeFiles = IncludeFiles0.Concat(IncludeFiles1).ToList();
                    if (IncludeFiles.Count > 0)
                    {
                        // Ensure file is created
                        if (!File.Exists(SourceFile))
                            File.Create(SourceFile).Close();
                        // Write the source file
                        using (var Writer = new StreamWriter(SourceFile))
                        {
                            Writer.WriteLine("// This file is generated by SB");
                            Writer.WriteLine("// It is used to generate compile commands for the project");
                            foreach (var IncludeFile in IncludeFiles)
                            {
                                Writer.WriteLine($"#include \"{IncludeFile}\"");
                            }
                        }
                    }
                    GenerateForFile(Target, CFamily.Cpp, SourceFile, null);
                }
            }
        }

        // merge dummy file list into compile_command file for clangd location
        var CompileCommandDummyFileList = Target.FileList<CompileCommandDummyFileList>();
        if (CompileCommandDummyFileList != null)
        {
            foreach (var f in CompileCommandDummyFileList.Files)
            {
                if (File.Exists(f))
                {
                    GenerateForFile(Target, CFamily.Cpp, f, null);
                }
                else
                {
                    Log.Warning("CompileCommandDummyFileList file {File} does not exist.", f);
                }
            }
        }

        return null;
    }


    public override bool EmitFileTask(BuildInstance Instance, Target Target, FileList FileList) => FileList.Is<CppFileList>() || FileList.Is<CFileList>() || FileList.Is<ObjCppFileList>() || FileList.Is<ObjCFileList>();
    public override IArtifact? PerFileTask(BuildInstance Instance, Target Target, FileList FileList, FileOptions? Options, string SourceFile)
    {
        Stopwatch sw = new();
        sw.Start();

        CFamily Language = FileList.Is<ObjCppFileList>() ? CFamily.ObjCpp : FileList.Is<ObjCFileList>() ? CFamily.ObjC : FileList.Is<CppFileList>() ? CFamily.Cpp : CFamily.C;
        GenerateForFile(Target, Language, SourceFile, Options);

        sw.Stop();
        AddElapsedMilliseconds(sw.ElapsedMilliseconds);
        return null;
    }

    public void WriteToFile(string path)
    {
        File.WriteAllText(path, "[" + String.Join(",", _compileCommands) + "]");
    }

    private void GenerateForFile(
        Target target,
        CFamily language,
        string sourceFile,
        FileOptions? fileOptions)
    {
        var sourceDependencies = Path.Combine(target.GetBuildSrcDepsDir(), BS.GetUniqueTempFileName(sourceFile, target.Name + this.Name, "source.deps.json"));
        var objectFile = GetObjectFilePath(target, sourceFile);
        var compilerArgumentDriver = Toolchain.Compiler.CreateArgumentDriver(target.Instance, language, false)
            .AddArguments(target.Arguments)
            .MergeArguments(fileOptions?.Arguments, true)
            .AddArgument("Source", sourceFile)
            .AddArgument("Object", objectFile)
            .AddArgument("SourceDependencies", sourceDependencies);

        var arguments = compilerArgumentDriver
            .CalculateArguments()
            .Values
            .SelectMany(argument => argument)
            .ToList();
        arguments.Insert(0, Toolchain.Compiler.ExecutablePath);

        var compileCommand = new CompileCommand
        {
            directory = target.Directory,
            arguments = arguments,
            file = sourceFile
        };
        var compileCommandJson = SB.Core.Json.Serialize(compileCommand);
        _compileCommands.Add(compileCommandJson);
        _compileCommandEntries.Add(new CompileCommandEntry(
            TargetName: target.Name,
            SourceFile: sourceFile,
            ObjectFile: objectFile,
            Directory: target.Directory,
            Arguments: arguments.ToArray()));
    }

    private static string GetObjectFilePath(Target target, string sourceFile) => Path.Combine(target.GetBuildObjsDir(), BuildInstance.GetUniqueTempFileName(sourceFile, target.Name, "obj"));

    private static bool HasCFamilyFiles(Target target) =>
        target.HasFilesOf<CppFileList>() ||
        target.HasFilesOf<CFileList>() ||
        target.HasFilesOf<ObjCppFileList>() ||
        target.HasFilesOf<ObjCFileList>();

    private readonly ConcurrentBag<string> _compileCommands = new();
    private readonly ConcurrentBag<CompileCommandEntry> _compileCommandEntries = new();
    private IToolchain Toolchain { get; }
}

public sealed record CompileCommandEntry(
    string TargetName,
    string SourceFile,
    string ObjectFile,
    string Directory,
    IReadOnlyList<string> Arguments);

public class CompileCommandDummyFileList : FileList
{
}

public static partial class TargetExtensions
{
    public static CppTarget AddCompileCommandDummyFiles(this CppTarget @this, params string[] files)
    {
        @this.FileList<CompileCommandDummyFileList>().AddFiles(files);
        return @this;
    }
}
