name: Setup Incant Toolchains AutoTest
description: Sets up .NET and builds the toolchain AutoTest executable.

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 10.0.x
        dotnet-quality: ga

    - name: Build AutoTest
      shell: pwsh
      run: |
        dotnet restore Tests/Incant.AutoTest.Toolchains/Incant.AutoTest.Toolchains.csproj
        dotnet build Tests/Incant.AutoTest.Toolchains/Incant.AutoTest.Toolchains.csproj --configuration Release --no-restore
