namespace SB.Core
{
    using ArgumentName = string;
    using BS = BuildInstance;

    /// <summary>
    /// Maps target properties to em++ link flags. em++ decides the final
    /// artifact format from the -o extension (.js -> JS glue + .wasm sidecar,
    /// .html -> full HTML shell, .wasm -> standalone).
    /// </summary>
    [ArgumentDriver(InjectType = typeof(CppTarget))]
    public class EmccLinkerArgumentDriver : IArgumentDriver
    {
        public EmccLinkerArgumentDriver(BuildInstance instance, Emscripten toolchain)
        {
            this.Toolchain = toolchain;
            if (instance.EmscriptenThreads)
                RawArguments.Add("-pthread");
        }

        [TargetProperty]
        public string TargetType(TargetType type) => typeMap.TryGetValue(type, out var t) ? t : throw new ArgumentException($"Invalid target type \"{type}\" for em++ linker!");
        static readonly Dictionary<TargetType, string> typeMap = new Dictionary<TargetType, string>
        {
            { Core.TargetType.Executable, "" },
            { Core.TargetType.Dynamic, "" }
        };

        [TargetProperty]
        public string OptimizationLevel(OptimizationLevel level) => level switch
        {
            // Link-time opt level mirrors compile; -flto at link is where LTO
            // actually runs the whole-program passes.
            SB.Core.OptimizationLevel.None => "-O0",
            SB.Core.OptimizationLevel.Fast => "-O1",
            SB.Core.OptimizationLevel.Faster => "-O2",
            SB.Core.OptimizationLevel.Fastest => "-O3 -flto",
            SB.Core.OptimizationLevel.Smallest => "-Oz -flto",
            _ => ""
        };

        [TargetProperty]
        public virtual string DebugSymbols(bool Enable) => Enable ? "-g" : "";

        [TargetProperty]
        public string Exception(bool Enable) => Enable ? "-fwasm-exceptions" : "-fno-exceptions";

        [TargetProperty(InheritBehavior = true, PathBehavior = true)]
        public string[]? LinkDirs(ArgumentList<string> dirs) => dirs.Select(dir => $"-L{dir}").ToArray();

        [TargetProperty(InheritBehavior = true)]
        public string[]? Link(ArgumentList<string> libs) => libs.Select(lib => $"-l{lib}").ToArray();

        // Emscripten-specific escape hatch for link-time -s<KEY>=<VAL> flags.
        // Fluent setter is auto-generated by the SourceGenerator so target
        // declarations can opt in with `.Emscripten_LinkerArgs(Visibility.Public,
        // "-sINITIAL_MEMORY=67108864", "-sEXPORTED_FUNCTIONS=['_main']")`.
        [TargetProperty(InheritBehavior = true)]
        public virtual string[] Emscripten_LinkerArgs(ArgumentList<string> flags) => flags.ToArray();

        public string[] Inputs(ArgumentList<string> inputs) => inputs.Select(f => $"\"{f}\"").ToArray();

        public string Output(string output) => BS.CheckFile(output, false) ? $"-o \"{output}\"" : throw new ArgumentException($"Invalid output file path {output}!");

        public ArgumentDictionary Arguments { get; } = new ArgumentDictionary();
        public HashSet<string> RawArguments { get; } = new HashSet<string>
        {
            "-sSTACK_SIZE=1048576",
            // Memory can grow at runtime — saner default for engine-sized heaps
            // than the fixed 16 MB that emcc ships with.
            "-sALLOW_MEMORY_GROWTH=1"
        };

        protected Emscripten Toolchain { get; }
    }
}
