<Project>
   <PropertyGroup>
      <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' == ''">$(MSBuildThisFileDirectory)..\build\.tools\$(MSBuildProjectName)\obj</BaseIntermediateOutputPath>
      <BaseOutputPath Condition="'$(BaseOutputPath)' == ''">$(MSBuildThisFileDirectory)..\build\.tools\$(MSBuildProjectName)\bin</BaseOutputPath>
      <NuGetAudit>false</NuGetAudit>
      <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
   </PropertyGroup>
</Project>
