<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Shared/FileSystemPath.cs" Link="FileSystemPath.cs" />
    <ProjectReference Include="../Incant.Base/Incant.Base.csproj" />
    <ProjectReference Include="../Incant.CXLegacy.Arguments.Generator/Incant.CXLegacy.Arguments.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
