<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../Source/Shared/FileSystemPath.cs" Link="Infrastructure/FileSystemPath.cs" />
    <ProjectReference Include="../../Source/Incant.CX/Incant.CX.csproj" />
    <ProjectReference Include="../Incant.AutoTest.CXToolchain.Shared/Incant.AutoTest.CXToolchain.Shared.csproj" />
    <None Update="Fixtures/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
